apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: data-infrastructure
build:
  artifacts:
  - image: dshacks/dshack-dw-job
    context: .
deploy:
  kubectl:
    manifests:
    - ./kubernetes/development/*