apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: data-infrastructure
build:
  artifacts:
  - image: dshacks/dshack-dw-job-development
    context: .
deploy:
  kubectl:
    manifests:
    - ./kubernetes/development/postgres.yaml
    - ./kubernetes/development/secret.yaml
    - ./kubernetes/development/cronjob.yaml
profiles:
# skaffold run -p migrate
# 新規DTOを追加した際に、development環境の全DBに対応するテーブルを作成する
- name: migrate
  deploy:
    kubectl:
      manifests:
      - ./kubernetes/development/postgres.yaml
      - ./kubernetes/development/secret.yaml
      - ./kubernetes/development/migration.yaml
# skaffold dev -p sync-test
# ファイルの保存と同期して、pytestによる自動ユニットテストを実施する
- name: sync-test
  deploy:
    kubectl:
      manifests:
      - ./kubernetes/development/postgres.yaml
      - ./kubernetes/development/secret.yaml
      - ./kubernetes/development/autotest.yaml
# skaffold run -p staging
- name: staging
  build:
    artifacts:
    - image: dshacks/dshack-dw-job-staging
      context: .
  deploy:
    kubectl:
      manifests:
      - ./kubernetes/staging/*
# skaffold run -p production
- name: production
  build:
    artifacts:
    - image: dshacks/dshack-dw-job-production
      context: .
  deploy:
    kubectl:
      manifests:
      - ./kubernetes/production/*

