# flake8: noqa
"""Initial

Revision ID: 2bd90d157593
Revises: None
Create Date: 2020-04-11 17:53:47.789540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd90d157593'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.String(length=16), nullable=False, comment='システム内で設定する企業毎に一意となるコード'),
    sa.Column('company_name', sa.String(length=256), nullable=False, comment='企業名'),
    sa.Column('stock_code', sa.String(length=16), nullable=False, comment='銘柄コード'),
    sa.Column('country_code', sa.String(length=16), nullable=False, comment='国コード'),
    sa.Column('listed_market', sa.String(length=32), nullable=False, comment='上場市場'),
    sa.Column('foundation_date', sa.DateTime(), nullable=True, comment='設立日(月)'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='本社所在地(経度)'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='本社所在地(緯度)'),
    sa.Column('ins_ts', sa.DateTime(), nullable=True),
    sa.Column('upd_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('company_id'),
    comment='企業の主要な情報をマスタとして格納する.日本の上場企業のみを対象.\n資本金・従業員数等の情報は時系列データなので、別テーブルで扱う'
    )
    op.create_table('stockprice',
    sa.Column('company_id', sa.String(length=16), nullable=False, comment='システム内で設定する企業毎に一意となるコード'),
    sa.Column('date', sa.Date(), nullable=False, comment='日付'),
    sa.Column('open_price', sa.Float(), nullable=True, comment='株価(始値)'),
    sa.Column('high_price', sa.Float(), nullable=True, comment='株価(高値)'),
    sa.Column('low_price', sa.Float(), nullable=True, comment='株価(安値)'),
    sa.Column('close_price', sa.Float(), nullable=True, comment='株価(終値)'),
    sa.Column('volume', sa.Float(), nullable=True, comment='出来高'),
    sa.Column('ins_ts', sa.DateTime(), nullable=True),
    sa.Column('upd_ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('company_id', 'date'),
    comment='企業毎の日毎の株価(始値・高値・安値・終値)・出来高を格納する'
    )
    op.create_table('stockprice_ma',
    sa.Column('company_id', sa.String(length=16), nullable=False, comment='システム内で設定する企業毎に一意となるコード'),
    sa.Column('date', sa.Date(), nullable=False, comment='日付'),
    sa.Column('ma_type', sa.String(length=16), nullable=False, comment='移動平均の計算条件(ex. sma5, ema25, ...)'),
    sa.Column('ma_value', sa.Float(), nullable=True, comment='ma_typeの条件下の移動平均株価'),
    sa.Column('ins_ts', sa.DateTime(), nullable=True),
    sa.Column('upd_ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('company_id', 'date', 'ma_type'),
    comment='企業毎の日次の移動平均株価(SMA・EMA・WMA)を格納する'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockprice_ma')
    op.drop_table('stockprice')
    op.drop_table('company')
    # ### end Alembic commands ###
